name: DispatchTask

on:
  schedule:
  - cron: "0,30 * * * *"
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Version
      run: |
        go version
        java -version
        python -V
        node -v
        npm -v
        git version
        docker -v

    - name: Which
      run: |
        which go
        which java
        which python
        which node
        which npm
        which git
        which docker
