name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  KEY1: ${{ secrets.KEY1 }}
  KEY2: ${{ secrets.KEY2 }}

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18
    - name: Build
      run: go build -o app
    - name: Run
      run: ./app
    - name: Clear
      run: rm -rf app
