name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: ReadSecrets
      run: |
        echo ${{ secrets.KEY1 }} > key1.txt
        echo ${{ secrets.KEY1 }} > key2.txt
        ls -l
        cat key1.txt
        cat key2.txt
    - name: Build
      run: go build -o app
    - name: Run
      run: ./app
    - name: Clear
      run: rm -rf key1.txt key2.txt app
