name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

env:
  CLIENT_ID: ${{ secrets.CLIENT_ID }}
  CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18
    - name: Go Download
      run: go mod download
    - name: Build
      run: go build -o app
    - name: Run
      run: |
        rm -rf app.log
        ./app
        echo `date +"%Y-%m-%d %H:%M:%S"` > time.log
        cat app.log
    - name: Clear
      run: rm -rf app
    - name: Commit #上传新的refresh_token到仓库
      run: |
        git config --global user.email robot@githubaction.com
        git config --global user.name robot
        git add .
        git commit -m "save by robot" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
